<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Nullable>disable</Nullable>                <!-- Disable nullable reference types for this project -->
        <ImplicitUsings>disable</ImplicitUsings>    <!-- Disable implicit usings for this project -->
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Counter.fs"/>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup/>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Diagnostics" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.FuncUI" />
        <PackageReference Include="Avalonia.FuncUI.Elmish" />
<!--        <PackageReference Include="JaggerJo.Avalonia.FuncUI" />-->
<!--        <PackageReference Include="JaggerJo.Avalonia.FuncUI.DSL" />-->
<!--        <PackageReference Include="JaggerJo.Avalonia.FuncUI.Elmish" />-->
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove=".template.config\**"/>
    </ItemGroup>

</Project>
