<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Akka.TestKit.NUnit" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AetherFlow.Domain\AetherFlow.Domain.csproj" />
    <ProjectReference Include="..\AetherFlow.Shared\AetherFlow.Shared.csproj" />
  </ItemGroup>

</Project>
